name: Run Cucumber Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Run Docker container
        id: run-docker
        run: docker run my-java-app
        continue-on-error: true

      - name: Check for test failures
        if: ${{ failure() }}
        run: echo "WARNING: Some tests failed. Please check the report."

      - name: Upload Cucumber Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber-reports/