name: Run Cucumber Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Run Docker container
        run: docker run -v ${{ github.workspace }}/target:/app/target --user $(id -u):$(id -g) my-java-app

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber-reports/