name: Run Cucumber Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Run Docker container and execute tests
        id: run-docker
        run: |
          docker run --name my-java-app-container my-java-app
#          docker cp my-java-app-container:/app/target/cucumber-reports ./target/cucumber-reports
#
#      - name: Check for test failures
#        if: ${{ failure() }}
#        run: |
#          echo "WARNING: Some tests failed. Please check the report."
#
#      - name: Upload Cucumber Report
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: cucumber-report
#          path: ./target/cucumber-reports
#
#      - name: Stop and remove Docker container
#        run: |
#          docker stop my-java-app-container
#          docker rm my-java-app-container